### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by BSMan1011** [entrippy/OctoPrint-OctoHue#16]
Hanging during install, here is my log, after it just keeps saying 
Building wheel for numpy (setup.py): still running...
Building wheel for numpy (setup.py): still running...
and so on until it timesout
[log.txt](https://github.com/entrippy/OctoPrint-OctoHue/files/4156910/log.txt)
Currently haven't tried manual install yet but will tomorrow, it is a fresh octiprint image

**Comment by entrippy** [comment]
So the obvious take out from this is that its numpy thats stalling for some reason (and it can take a while).
I'd try sshing in and after sourcing the virtualenv using pip to install numpy and seeing if it completes.

If it does jump back into octopi and try installing octohue by the plugin manager again.

**Comment by gennacide** [comment]
this is what happened to me and now it won't show up no matter what i do.

**Comment by entrippy** [comment]
@BSMan1011 , any luck with this? were you able to install numpy manually using pip and the CLI? Do you need guidance on how to try this?

**Comment by BSMan1011** [comment]
Unfortunately was unable to test tonight, but will try tomorrow, thanks for your help and I'll keep you updated

**Comment by BSMan1011** [comment]
I got it installed by using your `pip install --upgrade --force-reinstall https://github.com/entrippy/OctoPrint-OctoHue/archive/master.zip` command from other thread, i then used GUI to actually get showing up

**Comment by entrippy** [comment]
Happy days. let me know if you run into any other issues. Dont be afraid to give me a shout with any further problems or feature requests.
