### ISSUE TITLE
Can't access CLIP API Debugger 

### ISSUE THREAD

**Issue by Millerboy3** [entrippy/OctoPrint-OctoHue#19]
no matter what I do I can't get a response from this. Which is making this awesome plugin useless. I have already added an extension to attempt to bypass the access issue to no avail. Any suggestions?

SOLVED: Had to use firefox.

**Comment by entrippy** [comment]
Hi @Millerboy3 sorry I missed this. Incase you have similar issues in future, I use postman for doing API work.
