### ISSUE TITLE
Cannot delete status'

### ISSUE THREAD

**Issue by cjyoda78** [entrippy/OctoPrint-OctoHue#35]
I can add status' but every time i delete them, save, and log back into octoprint they have returned.

**Comment by entrippy** [comment]
Yup, this is something I am aware of and working on now. Should hopefully have it fixed shortly

**Comment by readeral** [comment]
Still having this issue unfortunately

**Comment by entrippy** [comment]
This has been resolved in 0.4.4.
I would recommend a reinstall of octogue including removing its settings, or alternatively deleting statusDict from config.yaml if your comfortable doing so.
