### ISSUE TITLE
Getting error when looking for light numbers. 

### ISSUE THREAD

**Issue by cellfreak** [entrippy/OctoPrint-OctoHue#36]
[{"error":{"type":1,"address":"/lights","description":"unauthorized user"}}]

**Comment by entrippy** [comment]
Did you follow the setup instructions and create yourself an api key on your hue bridge?

**Comment by entrippy** [comment]
Given the error, I'm assuming you didn't create a hue API key. 
Feel free to reopen this if thats not the case.
