### ISSUE TITLE
Light not turning on on Octoprint boot

### ISSUE THREAD

**Issue by philipptrenz** [entrippy/OctoPrint-OctoHue#38]
Hey there, thanks for your great work!

to my situation: My Pi with Octoprint is powered by the printers PSU, so that Octoprint starts when I power up the printer.

 I'd like to indicate when Octoprint is booted up, but neither the "Startup" event nor the "Connected" (I have it at "Autoconnect on boot") seem to fire. I guess the events are firing before the plugin gets initiated.

So I'd suggest another configurable event, which gets executed on initialization of the plugin 👍🏼

What do you think? ;)

**Comment by entrippy** [comment]
Thanks for the raising the issue. I need to give it more consideration, but i could potentually fix this with a "illuminate on startup" setting that octohue can look for as it boots.

Should be easy to implement, but give me some time to consider how to lay it out.

**Comment by entrippy** [comment]
@philipptrenz I added this in 0.5.0
To avoid an entirely seperate settings section after ticking "Turn on at startup" you should select an "event" that you have configured.
