### ISSUE TITLE
Plugin installed but not seen by Octoprint (install Unknown)

### ISSUE THREAD

**Issue by vantaingo** [entrippy/OctoPrint-OctoHue#39]
Hi,
I have an issue installing the plugin after a recent update of Octoprint to version 1.4.0 on OctoPi 0.17.0.
The plugin installation goes through until Octoprint requires a restart:

```
Plugin management log
Install Unknown: 
A restart is needed for the changes to take effect.
```

After the restart, the plugin is not visible.

I retried many times to reinstall it but without any success.
Same result when I do a manuel installation via SSH.

**Comment by galoki** [comment]
same here

**Comment by Jese44** [comment]
Yup, same here after upgrading to python 3.... so not sure if problem is this plugin or the python 3 upgrade

**Comment by galoki** [comment]
yep.  been having the same issue since 1.4.  I had to drop back to OctoPi .17 to use it.  I've brought this up months ago and never got a response.

**Comment by adcurtin** [comment]
easy fix:

run `sudo apt-get install libatlas-base-dev` in the cli. then reinstall octohue (via ui is fine). 


I looked at octoprint.log, tthere was a numpy import failure. it has a link to this page: https://numpy.org/devdocs/user/troubleshooting-importerror.html which has that as one of the solutions (apt install python3-numpy did not work for me, I had to use libatlas-base-dev)

**Comment by Jese44** [comment]
Thanks @adcurtin it worked for me!

**Comment by galoki** [comment]
> easy fix:
> 
> run `sudo apt-get install libatlas-base-dev` in the cli. then reinstall octohue (via ui is fine).
> 
> I looked at octoprint.log, there was a numpy import failure. it has a link to this page: https://numpy.org/devdocs/user/troubleshooting-importerror.html which has that as one of the solutions (apt install python3-numpy did not work for me, I had to use libatlas-base-dev)

@adcurtin thank you!

**Comment by moof-src** [comment]
I also tried updating OctoPrint from 1.4.0 to 1.5.0.  This downgraded my python from 3.7.3 to 2.7.16.  When I switched back to python 3.7.3 I found that all of my plugins worked except for OctoHue which was missing.  Installing gave the errors seen above with NumPy not working.  Please update your dependencies and fix this.  Thank you.  I love having the status of the printer attached to hue lights in my house.

**Comment by entrippy** [comment]
I just nuked my numpy install and then reinstalled octohue and it installed numpy and octohue successfully. 
I know this was some time ago, but i need more information on replicating this to fix the problem

I hate to say "works for me"... but it works for me
