### ISSUE TITLE
[BUG] Changes to Status Colours Not Saving

### ISSUE THREAD

**Issue by jerryfudd** [entrippy/OctoPrint-OctoHue#40]
**Describe the bug**
I delete one or more of the Status Colours using the trash bin and save, go back into the settings and my changes have held.

Then refresh the browser window, go back into Settings and all the Status Colours have returned to default.

All I would like OctoHue to do is sit on the menu bar for easy on/off of a lamp and not have any automation.

**To Reproduce**
As above

**Expected behavior**
Settings to remain as I set them

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 86.0.4240.193

**Additional context**

**Comment by entrippy** [comment]
Returning to this project. 
Yep, this bug is #1 on my list. no statuses are saved. 
Looking at it now

**Comment by entrippy** [comment]
released 0.4.4 which has resolved this bug.
I would recommend a plugin reinstall as the new config layout in config.yaml isn't compatible with the old version.
Dont forget to back up you hue api key
