### ISSUE TITLE
Feature Request: Turn on/off at events

### ISSUE THREAD

**Issue by YpsilonTM** [entrippy/OctoPrint-OctoHue#45]
I don't know if this project is abandoned.
But a really nice feature would be to simply turn on a light when starting to print and turn off that light when the print is done.

Greetings Ypsilon

**Comment by entrippy** [comment]
not abandoned... but sleeping... deep beneath thewaves.

you should be able to use PrintStarted and your desired light colour/brightness, and PrintCompleted with turnoff to accomplish this.
