### ISSUE TITLE
Feature request: shutdown light when octoprint is shutdown

### ISSUE THREAD

**Issue by hixfield** [entrippy/OctoPrint-OctoHue#6]
Just installed the plug-in, its great for the first version, keep up the good work!

I think when octoprint shutdown, you should also switch off the light.
Maybe you can make it an checkbox-option if it would not be applicable to all users ;-)

**Comment by entrippy** [comment]
Fair call, the original release included lights off on disconnect, but not on shutdown.
I've added lights off on shutdown and the corresponding checkbox (default to on)  to 0.3.1
