### ISSUE TITLE
Planned Feature: Light on/off toggle

### ISSUE THREAD

**Issue by entrippy** [entrippy/OctoPrint-OctoHue#8]
Add fearure to toggle the light or group on/off from within octoprint. This would be more convenient than having to make changes using an external app or switch.

Possible solutions:
* Bulb icon in Nav bar.
* Light control screen accessible via the Tabs bar.

**Comment by hixfield** [comment]
But... what color then to set the lights? The connect, print ok or error color?

**Comment by entrippy** [comment]
Most likely just a white light, I can't really think of a reason why someone would want to turn a light back on with a particular status colour (one exception would be if someone operated a print farm and wanted a visual indicator to identify a particular printer and its status).

The main use case for this in my head is toggling an enclosure light to check on build progress, or alternatively clearing a status colour back to white so the user can perform a physical task with good lighting. Or if a print is underway, turn the light off to reduce power, distractions etc.

**Comment by adcurtin** [comment]
I would use this to turn on the light while printing, and either change the color or turn it off when done printing. That makes it so I can monitor it remotely, and makes octolapse take better pictures. can't wait for this one :)

**Comment by entrippy** [comment]
@adcurtin the light Already flips on when octoprint connects to the printer and when the status changes to printing.  When printing is complete the light changes to green by default, orange if the job is paused (warning), and red if there is a failure or its cancelled.

Giving an option to switch off when done, and also perhaps off after X time once printing starts sounds like reasonable requests.

I've raised https://github.com/entrippy/OctoPrint-OctoHue/issues/17 to allow "off" as a status option.
and https://github.com/entrippy/OctoPrint-OctoHue/issues/18 as a place holder for the timer.

The latter will be further back in priorities as I need to give some thought into the entire subject of timing, which might have some impact to how this is designed.

**Comment by entrippy** [comment]
Delivered in 0.4.0
